### ISSUE TITLE
Not working since a few days

### ISSUE THREAD

**Issue by Tysonpower** [pagekit/extension-analytics#5]
I use pagekit and the analytics plugin since a year or so.

A few days ago the plugin unfortunately stopped working.

The Widgets are only showing a loading animation and after disconnecting it from Analytics i am not able to authenticate with the google api again :( After entering the authentication code from google, i only get a loading circle again.

![image](https://cloud.githubusercontent.com/assets/13482963/24113797/323fdba0-0d9e-11e7-90ab-935d276699e0.png)

I'am running the newest Pagekit version (1.0.11).

Please fix the Bug, could be a change in the Google api i would guess.

**Comment by MalteScharenberg** [comment]
The forever spinning loading animation was caused by missing error handling of API requests (we will fix this). But for me worked reauthenticating with Google. Is the error permanent?

**Comment by Tysonpower** [comment]
@MalteScharenberg I tried reauthenticate with google a few times now in the past days.

I even tried it some minutes ago and it was spinning for 5min before i give up.
So it seems to be permanent.

Any idea why that happens?

**Comment by MalteScharenberg** [comment]
Can you provide the response of that request?

**Comment by Tysonpower** [comment]
@MalteScharenberg Which response do you mean? I only get the spinning circle after entering the auth code. I get no other response other than that.

**Comment by MalteScharenberg** [comment]
Depending on your browser you can inspect all requests a website initiates. I'talking about the last request you can see in the network inspector.

**Comment by Tysonpower** [comment]
@MalteScharenberg i could have even come on to that.....i get the following error at the Request:

`POST /index.php/admin/analytics/code 400 (Bad Request)
(anonymous) @ VM49:1
(anonymous) @ vue.js?v=ea3d:22
F @ vue.js?v=ea3d:22
U @ vue.js?v=ea3d:22
Y @ vue.js?v=ea3d:22
(anonymous) @ vue.js?v=ea3d:22`

The response from the server on Googles side was the following:

`message
:
"file_get_contents(https://accounts.google.com/o/oauth2/token): failed to open stream: no suitable wrapper could be found"`

hope that helps :)

**Comment by MalteScharenberg** [comment]
Did you change your server environment? This looks like your [https file stream wrapper](http://php.net/manual/en/wrappers.http.php) is missing?

**Comment by Tysonpower** [comment]
@MalteScharenberg thanks for the tipp, made a short php file to show me the variable.

Really seems to be empty.....i will talk to my Server hoster (it's a webspace).

**Comment by Tysonpower** [comment]
@MalteScharenberg got it! Thanks for your help.
Because of something (a bug while changing Server Setup a weeks ago) the server conf had fopen deactivated.
