### ISSUE TITLE
Where is the settings page?

### ISSUE THREAD

**Issue by kiamlaluno** [pagekit/extension-analytics#8]
I installed the extension from the marketplace page shown on my site, but I am not able to access the settings page for the extension. From other issues, I get I should enter a request code, but I don't see any place where I can insert it.

The extension version shown from admin/system/package/extensions is 1.0.1.

**Comment by kiamlaluno** [comment]
I also tried removing it to re-add it. I get a dialog box showing the following output.

```
Loading composer repositories with package information
Updating dependencies
  - Installing lusitanian/oauth (v0.3.6)
    Downloading

  - Installing pagekit/analytics (1.0.1)
    Downloading

Writing lock file
Generating optimized autoload files
```

In that dialog box, I click on the _Enable_ button shown at the bottom.

**Comment by lucaslcode** [comment]
@kiamlaluno did you ever resolve this? Same problem here

**Comment by lucaslcode** [comment]
In my case it was my browser's address blocker stoping the script loading.

**Comment by kiamlaluno** [comment]
Thank you. It seems I resolved it too. 

I disabled uBlock Origin, and went to /admin/dashboard. I clicked "Add widget" and chose "Analytics"; the dialog box that appears requires some parameters, and it contains the following text.

> Google Analytics authentication needed.

Clicking on _authentication_ opened a new dialog box that allowed me to request a code.
